# -*- coding: utf-8 -*-
"""web scraping food data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OzUkHutrBTRDpI27C05TOGnxoUGPiB2_

# **Web Scraping Images from Amazon website**
"""

import requests
from bs4 import BeautifulSoup
import os

def imagedown(url, folder):
    try:
        os.mkdir(os.path.join(os.getcwd(), folder))
    except:
        pass
    os.chdir(os.path.join(os.getcwd(), folder))
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')
    images = soup.find_all('img')
    images=images[2:]
    images=images[:-8]
    for image in images:
        name = image['alt']
        link = image['src']
        with open(name.replace(' ', '-').replace('/', '') + '.jpg', 'wb') as f:
            im = requests.get(link)
            f.write(im.content)
            print('Writing: ', name)

imagedown('https://www.amazon.com.au/s?k=airbuds&crid=1Y7O6SQ3B8OOQ&sprefix=airbu%2Caps%2C339&ref=nb_sb_ss_ts-a-p_1_5', 'amazon_airbuds')