# -*- coding: utf-8 -*-
"""web scraping food data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OzUkHutrBTRDpI27C05TOGnxoUGPiB2_

# **Web Scraping Images from Amazon website**
"""

import requests
from bs4 import BeautifulSoup
import os

def imagedown(url, folder):
    os.mkdir(os.path.join(os.getcwd(), folder))
    os.chdir(os.path.join(os.getcwd(), folder))
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')
    images = soup.find_all('img')
    for image in images:
        name = image['alt']
        link = image['src']
        with open(name.replace(' ', '-').replace('/', '') + '.jpg', 'wb') as f:
            im = requests.get(link)
            f.write(im.content)
            print('Writing: ', name)

imagedown('https://www.amazon.com.au/s?k=airbuds&crid=1Y7O6SQ3B8OOQ&sprefix=airbu%2Caps%2C339&ref=nb_sb_ss_ts-a-p_1_5', 'amazon_airbuds')

import os

path = '/content/amazon_airbuds/'

import os
print(os.walk("."))  #Nothing to see here as this is just a generator object

# traverse root directory, and list directories as dirs and files as files
for root, dirs, files in os.walk("."):
    #print(root)  #Prints root directory names
    
    path = root.split(os.sep)  #SPlit at separator (/ or \)
    #print(path)  #Gives names of directories for easy location of files
    #print(files)   #Prints all file names in all directories
    
#Let us now visualize directories and files within them
    print((len(path) - 1) * '---', os.path.basename(root)) #Add --- based on the path
    for file in files:
        print(len(path) * '---', file)

#import the library opencv
import cv2
import glob

file_list = glob.glob('/content/amazon_airbuds/*.*') #Rerurns a list of file names
#print(file_list)  #Prints the list containing file names

#Now let us load each file at a time...
my_list=[]  #Empty list to store images from the folder.
path = '/content/amazon_airbuds/*.*'
for file in glob.glob(path):   #Iterate through each file in the list using for
    #print(file)     #just stop here to see all file names printed
    a= cv2.imread(file)  #now, we can read each file since we have the full path
    my_list.append(a)  #Create a list of images (not just file names but full images)
    
#View images from the stored list
import matplotlib.pyplot as plt

plt.figure(figsize=(15,25))
for i in range(48):
    plt.subplot(6,8,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(my_list[i], cmap=plt.cm.binary)
plt.show()